platform:ios,'7.0'
source 'https://github.com/CocoaPods/Specs.git'

#pod 'libextobjc/EXTScope', '~> 0.4.1'

pod 'MMDrawerController', '~> 0.6.0'

pod 'MagicalRecord', '~> 2.3.0'
pod 'Masonry', '~> 0.6.2'

pod 'AMapNavi', '~> 1.3.1'

pod 'Base64nl', '~> 1.2'
pod 'Reachability', '~> 3.2'
pod 'AFNetworking', '~> 2.5.4'

pod 'Mantle', '~> 2.0.2'

#pod 'RHToolkits', :git=>"https://github.com/zhu410289616/RHToolkits.git"
#先把私有库clone到本地，然后通过指定［path］或者［podspec］调用
#pod repo add RHToolkits https://github.com/zhu410289616/RHToolkits.git
pod 'RHToolkits', :podspec=>"~/.cocoapods/repos/RHToolkits/RHToolkits.podspec"  #指定podspec文件
#pod 'RHToolkits/RHMapKit', :podspec=>"~/.cocoapods/repos/RHToolkits/RHToolkits.podspec"  #指定podspec文件


#pod 'RHSocketKit', :git=>"https://github.com/zhu410289616/RHSocketKit.git"

#先把私有库clone到本地，然后通过指定［path］或者［podspec］调用
#pod repo add RHSocketKit https://github.com/zhu410289616/RHSocketKit.git
#pod 'RHSocketKit', :path=>"~/.cocoapods/repos/RHSocketKit"  #指定路径
pod 'RHSocketKit', :podspec=>"~/.cocoapods/repos/RHSocketKit/RHSocketKit.podspec"  #指定podspec文件


